### PR TITLE
Integrate quick app installation script.

### PR DESCRIPTION
**Pull request by ruchit-viitorcloud**
-  Integrate quick app installation script.
-   Create install.sh file.
-   Create console command "install:app".
-   Add checkDatabaseConnection function in helper file.
-   Add default database SQL file which is used while dumping the default database directly.

### CODE REVIEW

**Comment by bvipul** [comment]
I would say, this is nice, but we have migrations and seed, so I would prefer if the script runs those commands instead of dumping the sql.

**Comment by viralsolani** [comment]
@ruchit-viitorcloud  Thanks for this PR. Please write the necessary steps in the readme as well.

**Comment by ruchit-viitorcloud** [comment]
> I would say, this is nice, but we have migrations and seed, so I would prefer if the script runs those commands instead of dumping the sql.

Hello @bvipul , I have already added those commands.
When any user runs the script at that time script populate with options like,  "You want to dump database sql ? ". If user select no at that time script continue as it is and new options populate with "You want to migrate tables ?" and after that "You want to seed your database? "

Let me know if you need any help with the same script.

Thanks.

**Comment by ruchit-viitorcloud** [comment]
> Hello ruchit, I know you have added those methods, but the thing is, the options for running migrations And seeds should be mandatory, because without those the app won't run. So, you just need to remove asking them if they want to run migrate/seeds and migrate and seed for them. I hope I am clear. Do tell, if you have anything to add

@bvipul  done, could you please check and update me.

**Pull request merged**
