### PR TITLE
Fixed table names from FaqsRepository

### PR DESCRIPTION
**Pull request by emir**
I think copy paste mistake. Now fixed.

### CODE REVIEW

**Comment by bvipul** [comment]
Oops, thanks, you saved our lives. :smiley:

**Comment by bvipul** [comment]
Hello @emir, can you please change the PR branch to develop, we will release this with other bug fixes.
thanks.

**Comment by emir** [comment]
@bvipul Hello I checked README for contribution guideline but I haven't see when I submit this PR. I've already deleted repository. Can you do that?

**Comment by bvipul** [comment]
Did it. Added it in another commit.

**Pull request closed without merging**
